
# TR

# Categorys
GFL2.Category.Paradeus=Paradeus
GFL2.Category.PMC=Private Military Contractor
GFL2.Category.URNC=URNC
GFL2.Category.ELID=E.L.I.D.
GFL2.Category.Mokosh=Mokosh
GFL2.Category.MangiSecurity=Mangi Security Service
GFL2.Category.Varjagers=Varjagers
GFL2.Category.Orlog=Orlog Conglomerate
GFL2.Category.Marley=Marley Thermal Power Plant

# Aegis SWAP
GFL2.Aegis_SWAP_Artillery_PM=Girls Frontline 2 Aegis SWAP Artillery
GFL2.Aegis_SWAP_Bulwark_PM=Girls Frontline 2 Aegis SWAP Bulwark
GFL2.Aegis_SWAP_Dominator_PM=Girls Frontline 2 Aegis SWAP Dominator
GFL2.Aegis_SWAP_Myrmidon_PM=Girls Frontline 2 Aegis SWAP Myrmidon

GFL2.Aegis_SWAP_Artillery_NPC_F=Aegis SWAP Artillery (Dost)
GFL2.Aegis_SWAP_Artillery_NPC_E=Aegis SWAP Artillery (Düşman)
GFL2.Aegis_SWAP_Bulwark_NPC_F=Aegis SWAP Bulwark (Dost)
GFL2.Aegis_SWAP_Bulwark_NPC_E=Aegis SWAP Bulwark (Düşman)
GFL2.Aegis_SWAP_Dominator_NPC_F=Aegis SWAP Dominator (Dost)
GFL2.Aegis_SWAP_Dominator_NPC_E=Aegis SWAP Dominator (Düşman)
GFL2.Aegis_SWAP_Myrmidon_NPC_F=Aegis SWAP Myrmidon (Dost)
GFL2.Aegis_SWAP_Myrmidon_NPC_E=Aegis SWAP Myrmidon (Düşman)

GFL2.Aegis_SWAP_Artillery_Description=An upgraded version of the Aegis, essentially a mobile turret that prides itself on its cyclic rate and high firepower, ensuring victory for you and your team from the starting line.\n\nStart at range, seize the day!
GFL2.Aegis_SWAP_Bulwark_Description=An upgraded version of the Aegis. Its improvements are focused on its defensive systems, making it tougher and more durable, like what one would expect of the name "Bulwark".\n\nFull of security, full of love.
GFL2.Aegis_SWAP_Dominator_Description=One of the upgraded versions of the Aegis series, equipped with several Centralized Goliaths. Gain the powerful combination of Aegis and Goliath with just one small additional payment. Order now!\n\nAfter fighting, they can also come together to play poker.
GFL2.Aegis_SWAP_Myrmidon_Description=An upgraded version of the Aegis. It now focuses on variable attack methods, allowing it to choose from the best option to suit the field conditions. Ever-changing and dynamic, so just take your pick.\n\nThe Aegis Myrmidon, providing you with a professional and versatile solution to the enemy.

# Ateraxis
GFL2.Ateraxis_PM=Girls Frontline 2 Ateraxis
GFL2.Ateraxis_NPC_F=Ateraxis (Dost)
GFL2.Ateraxis_NPC_E=Ateraxis (Düşman)

GFL2.Ateraxis_Description=Caldwell tarafından geliştirilen, üçüncü nesil özel bir T-Doll'dur. Kendi hücreleri üzerinde mutlak kontrole sahiptir ve bunları dilediği gibi çeşitli ölümcül silahlara dönüştürerek savaşabilir. Son derece yüksek yıkıcı güce sahiptir. Karmaşık durumlarla karşılaştığında ise, çoğu zaman bir çocuğun saflığını andıran masum ama acımasız bir tavır sergiler.\n\n“Ablasını” yemeyi reddetmesinin nedeni, bir çocuk gibi yemek seçmesidir.

# Cocoon
GFL2.Cocoon_PM=Girls Frontline 2 Cocoon
GFL2.Cocoon_NPC_F=Cocoon (Dost)
GFL2.Cocoon_NPC_E=Cocoon (Düşman)

GFL2.Cocoon_Description=Görünürde nazik ama aslında çok soğuk bir Bebek. Bu 3. nesil Bebek istihbarat toplamada yetenekli ve harekete geçmeden önce strateji kurmayı seviyor. Düşmanın istihbaratını tamamen darmadağın ettikten sonra düşmanı adım adım işin içinden çıkılamaz bir duruma sokacak.\n\nI want to know all your secrets~

# Execution Squad
GFL2.ExecutionSquad_Blaster_PM=Girls Frontline 2 Blaster
GFL2.ExecutionSquad_Flyer_PM=Girls Frontline 2 Flyer
GFL2.ExecutionSquad_Mechanist_PM=Girls Frontline 2 Mechanist
GFL2.ExecutionSquad_Strike_Captain_PM=Girls Frontline 2 Strike Captain

GFL2.ExecutionSquad_Blaster_NPC_F=Blaster (Dost)
GFL2.ExecutionSquad_Blaster_NPC_E=Blaster (Düşman)
GFL2.ExecutionSquad_Flyer_NPC_F=Flyer (Dost)
GFL2.ExecutionSquad_Flyer_NPC_E=Flyer (Düşman)
GFL2.ExecutionSquad_Mechanist_NPC_F=Mechanist (Dost)
GFL2.ExecutionSquad_Mechanist_NPC_E=Mechanist (Düşman)
GFL2.ExecutionSquad_Strike_Captain_NPC_F=Strike Captain (Dost)
GFL2.ExecutionSquad_Strike_Captain_NPC_E=Strike Captain (Düşman)

GFL2.ExecutionSquad_Blaster_Description=Demolitionists carrying varieties of equipment and explosives. Provides key support fire or cover, as well as clearing out paths of attack.	\n\nWas fined on many occasions for setting off fireworks in violation of regulations.
GFL2.ExecutionSquad_Flyer_Description=The main body of a squad's firepower. Capable of flexibly traversing long distances on the battlefield via flight and delivering a fatal blow.\n\nInsecticide will do little to them, but it's not like you need to bring out the big guns.
GFL2.ExecutionSquad_Mechanist_Description=Operations in the field, whether combat or logistical in nature, rely upon mecha-hounds. The mechanists carry upon them many maintenance toolboxes for this reason.\n\nWas fined on many occasions for walking a pet without a leash.
GFL2.ExecutionSquad_Strike_Captain_Description=Becoming a core officer of Mangi Security requires outstanding management and command abilities as well as personal prowess. A Strike Captain is an expert in combat at a variety of ranges and is highly adaptable in the field, posing a lethal threat to any enemy.\n\nNo one knew of his infiltration. No one alive, at least.

# Gaia & Theia
GFL2.Gaia_PM=Girls Frontline 2 Gaia
GFL2.Gaia_NPC_F=Gaia (Dost)
GFL2.Gaia_NPC_E=Gaia (Düşman)

GFL2.Theia_PM=Girls Frontline 2 Theia
GFL2.Theia_NPC_F=Theia (Dost)
GFL2.Theia_NPC_E=Theia (Düşman)

GFL2.Gaia_Description=A cheerful and keen Tactical Doll. As a corporate test subject, her neural cloud uses cutting edge technology. Her melee weapon skills are highly refined and she is very confident in her strength and speed. Her sheer strength devastates all goes.\n\nAs if your little sister would be that cute.
GFL2.Theia_Description=A rational and experienced Tactical Doll. As a corporate test subject, her neural cloud uses cutting-edge technology. She uses custom-made weaponry and practically no prey has been able to escape the dangerous webs of high energy beams that she spins.\n\nYou said there'd be no overtime; how could you lie to me like that?

# Igla
GFL2.Igla_PM=Girls Frontline 2 Igla
GFL2.Igla_NPC_F=Igla (Dost)
GFL2.Igla_NPC_E=Igla (Düşman)

GFL2.Igla_Description=Kıyafetleri zarif olduğu gibi kendisi de bir o kadar zarif 3. nesil bir Bebek. Ağırbaşlı görünümünün altında hayranlık uyandıran olağanüstü bir güç saklıyor.\n\nAs polite and composed as a funeral.

# Iris
GFL2.Iris_PM=Girls Frontline 2 Iris
GFL2.Iris_NPC_F=Iris (Dost)
GFL2.Iris_NPC_E=Iris (Düşman)

GFL2.Iris_Description=[SİLİNDİ]\n\n[SİLİNDİ]

# Paradeus Doll
GFL2.Paradeus_Doll_PM=Girls Frontline 2 Paradeus Doll

GFL2.Paradeus_Doll_NPC_F=Paradeus Doll (Dost)
GFL2.Paradeus_Doll_NPC_E=Paradeus Doll (Düşman)

GFL2.Paradeus_Doll_Description=Paradus'a ait bir Bebek. Mükemmel dövüş gücüne ve eşsiz görev kabiliyetine sahip. Basit saldırı yöntemlerine rağmen güçlü silah parçaları onu hafife alınamayacak bir rakip haline getiriyor. Varlıklarını hiç sorgulamadan kaleyi koruma görevine devam ediyorlar.\n\nNereden bakarsanız bakın aynı görünebilirler fakat görünüşe aldanmayın.

# Mokosh
GFL2.Mokosh_Judge_PM=Girls Frontline 2 Oathsworn Judge
GFL2.Mokosh_Vanguard_PM=Girls Frontline 2 Oathsworn Vanguard
GFL2.Mokosh_Spec_Ops_PM=Girls Frontline 2 Oathsworn Spec Ops
GFL2.Mokosh_Support_PM=Girls Frontline 2 Oathsworn Support

GFL2.Mokosh_Judge_NPC_F=Oathsworn Judge (Dost)
GFL2.Mokosh_Judge_NPC_E=Oathsworn Judge (Düşman)
GFL2.Mokosh_Vanguard_NPC_F=Oathsworn Vanguard (Dost)
GFL2.Mokosh_Vanguard_NPC_E=Oathsworn Vanguard (Düşman)
GFL2.Mokosh_Spec_Ops_NPC_F=Oathsworn Spec Ops (Dost)
GFL2.Mokosh_Spec_Ops_NPC_E=Oathsworn Spec Ops (Düşman)
GFL2.Mokosh_Support_NPC_F=Oathsworn Support (Dost)
GFL2.Mokosh_Support_NPC_E=Oathsworn Support (Düşman)

GFL2.Mokosh_Judge_Description=An officer among the Mokosh Oathsworn. They are accomplished warriors and possess exceptional tactical skills. They report directly to the highest authority of Mokosh and oversee the battlefield, directing various forces during operations. They are also capable of fighting in urban combat environments and quelling small-scale insurgencies. Oathsworn Arbitrators are not just respected, they are feared. Without their loyalty, they are nothing.\n\nBattlefield judgement complete. You have the right to remain silent, but the noise you made is loud enough as it is.
GFL2.Mokosh_Vanguard_Description=These frontliners among the Oathsworn are responsible for suppressing riots and are largely composed of local militiamen. They primarily use numbers to make a chance for themselves for them to seize victory in close combat. Their gear is more valuable than their lives.\n\nWho says cannon fodder can't have dreams? At the very least, climbing the ranks through their achievements isn't wishful thinking for them.
GFL2.Mokosh_Spec_Ops_Description=Elite members of their Oathsworn, their equipment is better, their wills are stronger, and their careers are completely stagnated. They handle fire support among Oathsworn fireteams and boast excellent ranged combat abilities as well as a cruel, ruthless fighting style. One could say they are fanatics who represent Mokosh's ideology.\n\nDon't question their loyalty; they won't hesitate to show you its power.
GFL2.Mokosh_Support_Description=They handle logistics and medical duties in Oathsworn combat teams. Primarily composed of the elderly and veterans. While they have a limited ability to defend themselves, they're always the first to flee when trouble rears its ugly head.\n\nUsually, they're capable of helping their friends out, but when push comes to shove, they're nowhere to be found.

# Niter
GFL2.Niter_PM=Girls Frontline 2 Niter
GFL2.Niter_NPC_F=Niter (Dost)
GFL2.Niter_NPC_E=Niter (Düşman)

GFL2.Niter_Description=A cute girl who's always smiling and full of warmth. No matter how the battlefield changes, her gentle kindness will always stay the same.\n\nHer voice is kindly enough, but she isn't necessarily a friend.

# Nyto
GFL2.Nyto_PM=Girls Frontline 2 Nyto
GFL2.Nyto_NPC_F=Nyto (Dost)
GFL2.Nyto_NPC_E=Nyto (Düşman)

GFL2.Nyto_Description=[SİLİNDİ\n\n[SİLİNDİ]

# Sextans
GFL2.Paradeus_Sextans_PM=Girls Frontline 2 Sextans
GFL2.Paradeus_Lose_Sextans_PM=Girls Frontline 2 Sextans?

GFL2.Paradeus_Sextans_NPC_F=Sextans (Dost)
GFL2.Paradeus_Sextans_NPC_E=Sextans (Düşman)
GFL2.Paradeus_Lose_Sextans_NPC_F=Sextans? (Dost)
GFL2.Paradeus_Lose_Sextans_NPC_E=Sextans? (Düşman)

GFL2.Paradeus_Sextans_Description=Mükemmel bir satranç oyuncusu, tahtadaki her şeyi kullanabilir — düşmanın taşları dahil.\n\nYou are 14 minutes and 25.31 seconds late.
GFL2.Paradeus_Lose_Sextans_Description=Adını unutmuş bir satranç oyuncusu eskiden olduğu gibi sakince hamlesini yapıp geleceğe dair karar verebilir mi?\n\nSöyle... bana... ben... kimim?

# Shellcracker
GFL2.Shellcracker_NPC_E=Shellcracker

GFL2.Shellcracker.Description=A half-flora, half-fauna monster that has been severely mutated by Collapse Radiation. It boasts incredible destructive power and vitality and can shred armor with ease.\n\nThis thing... does it need sunlight and water?
