
# ZH-CN

# Categorys
GFL2.Category.Paradeus=帕拉蒂斯
GFL2.Category.PMC=P.M.C.
GFL2.Category.URNC=URNC
GFL2.Category.ELID=E.L.I.D.
GFL2.Category.Mokosh=莫科什
GFL2.Category.MangiSecurity=曼尼安保
GFL2.Category.Varjagers=瓦良格
GFL2.Category.Orlog=奥尔劳格财团
GFL2.Category.Marley=马利热电厂

# Aegis SWAP
GFL2.Aegis_SWAP_Artillery_PM=[少女前线 2] 重炮圣盾SWAP
GFL2.Aegis_SWAP_Bulwark_PM=[少女前线 2] 铁壁圣盾SWAP
GFL2.Aegis_SWAP_Dominator_PM=[少女前线 2] 御导圣盾SWAP
GFL2.Aegis_SWAP_Myrmidon_PM=[少女前线 2] 百式圣盾SWAP

GFL2.Aegis_SWAP_Artillery_NPC_F=重炮圣盾SWAP（友方）
GFL2.Aegis_SWAP_Artillery_NPC_E=重炮圣盾SWAP（敌对）
GFL2.Aegis_SWAP_Bulwark_NPC_F=铁壁圣盾SWAP（友方）
GFL2.Aegis_SWAP_Bulwark_NPC_E=铁壁圣盾SWAP（敌对）
GFL2.Aegis_SWAP_Dominator_NPC_F=御导圣盾SWAP（友方）
GFL2.Aegis_SWAP_Dominator_NPC_E=御导圣盾SWAP（敌对）
GFL2.Aegis_SWAP_Myrmidon_NPC_F=百式圣盾SWAP（友方）
GFL2.Aegis_SWAP_Myrmidon_NPC_E=百式圣盾SWAP（敌对）

GFL2.Aegis_SWAP_Artillery_Description=圣盾系列升级版之一，以高射速、强火力为卖点的移动式炮台。让您和您的队伍赢在起跑线上。\n\n远程开局，抢占先机！
GFL2.Aegis_SWAP_Bulwark_Description=圣盾系列升级版之一，着重升级了防御系统，使机体更加抗打、耐用，无愧于铁壁之名。\n\n满满的安全感，满满的爱。
GFL2.Aegis_SWAP_Dominator_Description=圣盾系列升级版之一，配备了数个集控式歌利亚。少许的价格提升，却能换到圣盾与歌利亚的强强联合，快来订购吧！\n\n作战之余，也能凑起来打扑克。
GFL2.Aegis_SWAP_Myrmidon_Description=圣盾系列升级版之一，主打攻击方式修正，能够根据情况选择最佳攻击方式。百般变化，任您选择。\n\n百式圣盾，为您提供灵活专业的对敌方案。

# Ateraxis
GFL2.Ateraxis_PM=[少女前线 2] 星渊
GFL2.Ateraxis_NPC_F=星渊（友方）
GFL2.Ateraxis_NPC_E=星渊（敌对）

GFL2.Ateraxis_Description=科德韦尔培育而成的特异三代人形。对自身细胞拥有绝对掌控力，能将其随意幻化为各类致命武器进行作战，杀伤力极强。在面对复杂事态时，她时常表现出如同婴孩般天真而纯粹的残忍。\n\n拒绝吞噬“姐姐”的真相，其实是小孩子挑食。

# Cocoon
GFL2.Cocoon_PM=[少女前线 2] 茧
GFL2.Cocoon_NPC_F=茧（友方）
GFL2.Cocoon_NPC_E=茧（敌对）

GFL2.Cocoon_Description=看似温柔实则阴冷的三代人形，擅长情报梳理，喜欢谋定而后动，将敌人的情报彻底拆解后，一步步将敌人引入绝境。\n\n你所有的秘密，我都想知道~

# Execution Squad
GFL2.ExecutionSquad_Blaster_PM=[少女前线 2] 爆破手
GFL2.ExecutionSquad_Flyer_PM=[少女前线 2] 游空兵
GFL2.ExecutionSquad_Mechanist_PM=[少女前线 2] 操械师
GFL2.ExecutionSquad_Strike_Captain_PM=[少女前线 2] 执行组长

GFL2.ExecutionSquad_Blaster_NPC_F=爆破手（友方）
GFL2.ExecutionSquad_Blaster_NPC_E=爆破手（敌对）
GFL2.ExecutionSquad_Flyer_NPC_F=游空兵（友方）
GFL2.ExecutionSquad_Flyer_NPC_E=游空兵（敌对）
GFL2.ExecutionSquad_Mechanist_NPC_F=操械师（友方）
GFL2.ExecutionSquad_Mechanist_NPC_E=操械师（敌对）
GFL2.ExecutionSquad_Strike_Captain_NPC_F=执行组长（友方）
GFL2.ExecutionSquad_Strike_Captain_NPC_E=执行组长（敌对）

GFL2.ExecutionSquad_Blaster_Description=携带各类火药与装置的爆破手，是清理进攻路线，提供火力支援或掩护的一把好手。\n\n曾因违规燃放烟花而被罚款数次。
GFL2.ExecutionSquad_Flyer_Description=小队的主要火力输出，可进行快速灵活飞行。游空兵借助背后装载的火力推进装置，可以在战场中进行长距离的移动，在空中给予敌人致命打击。\n\n杀虫剂对他们无效，不过，也不至于要动用大炮。
GFL2.ExecutionSquad_Mechanist_Description=无论是作战还是提供补给支援，都极度依赖机犬兵，这也是操械师们随身携带数个维修箱的原因。\n\n曾因遛宠不牵绳而被罚款数次。
GFL2.ExecutionSquad_Strike_Captain_Description=能够成为曼尼安保执行小队的核心人物，并不仅依靠优秀的管理和指挥能力，更是因为其本身实力强劲。执行组长擅长各种距离下的作战，再辅以优秀的战场应变能力，能够轻易给予敌人致命一击。\n\n没有人知道他潜入了，至少没有活人知道。

# Gaia & Theia
GFL2.Gaia_PM=[少女前线 2] 盖娅
GFL2.Gaia_NPC_F=盖娅（友方）
GFL2.Gaia_NPC_E=盖娅（敌对）

GFL2.Theia_PM=[少女前线 2] 希娅
GFL2.Theia_NPC_F=希娅（友方）
GFL2.Theia_NPC_E=希娅（敌对）

GFL2.Gaia_Description=爽朗尖锐的战术人形。身为财团实验体，其心智科技运用了前沿技术。使用近身武器的技巧炉火纯青，对自身的力量与速度十分自豪。绝对的实力，让敌人万念俱灰。\n\n你的妹妹哪有这么可爱。
GFL2.Theia_Description=理智干练的战术人形。身为财团实验体，其心智科技运用了前沿技术。装载有特殊定制武器，几乎没有猎物能逃出她用高能量射线编织起的危险网格。\n\n说好的不加班，怎么是骗人的？

# Igla
GFL2.Igla_PM=[少女前线 2] 针
GFL2.Igla_NPC_F=针（友方）
GFL2.Igla_NPC_E=针（敌对）

GFL2.Igla_Description=衣着考究、举止优雅的第三代人形，在精心维持的体面外表下，潜藏着令人敬畏的非凡力量。\n\n她礼貌得像是来参加葬礼。

# Iris
GFL2.Iris_PM=[少女前线 2] 鸢尾花
GFL2.Iris_NPC_F=鸢尾花（友方）
GFL2.Iris_NPC_E=鸢尾花（敌对）

GFL2.Iris_Description=由科德韦尔所研发的三代人形，一心只为母亲服务，守护着帕拉蒂斯。优雅古典的外表是她最好的伪装，只有被她亲自“教导”过的人，才明白隐藏于其下的可怖实力。\n\n小心，她会悉心“教导”每一个不听话的孩子。

# Paradeus Doll
GFL2.Paradeus_Doll_PM=[少女前线 2] 帕拉蒂斯人形

GFL2.Paradeus_Doll_NPC_F=帕拉蒂斯人形（友方）
GFL2.Paradeus_Doll_NPC_E=帕拉蒂斯人形（敌对）

GFL2.Paradeus_Doll_Description=从属于帕拉蒂斯的人形，拥有强大的战斗力和优秀的执行能力。尽管攻击手段单一，但其所搭载的强大火力控件，让她们成为不容小觑的对手。这些人形尽职尽责地充当着古堡的护卫者，无暇思索自己为何会出现在这里。\n\n虽然无论从哪个方面看都很眼熟，但可千万别认错人了。

# Mokosh
GFL2.Mokosh_Judge_PM=[少女前线 2] 誓卫仲裁官
GFL2.Mokosh_Vanguard_PM=[少女前线 2] 先锋誓卫
GFL2.Mokosh_Spec_Ops_PM=[少女前线 2] 特战誓卫
GFL2.Mokosh_Support_PM=[少女前线 2] 支援誓卫

GFL2.Mokosh_Judge_NPC_F=誓卫仲裁官（友方）
GFL2.Mokosh_Judge_NPC_E=誓卫仲裁官（敌对）
GFL2.Mokosh_Vanguard_NPC_F=先锋誓卫（友方）
GFL2.Mokosh_Vanguard_NPC_E=先锋誓卫（敌对）
GFL2.Mokosh_Spec_Ops_NPC_F=特战誓卫（友方）
GFL2.Mokosh_Spec_Ops_NPC_E=特战誓卫（敌对）
GFL2.Mokosh_Support_NPC_F=支援誓卫（友方）
GFL2.Mokosh_Support_NPC_E=支援誓卫（敌对）

GFL2.Mokosh_Judge_Description=莫科什誓卫军中的将官，战功赫赫，具备过人的战术素养。他们直接接受莫科什最高领袖的调令，总管战场，指挥多兵种进行联队作战。比起受人尊敬，誓卫仲裁官更多的受到人们的恐惧。离开忠诚，他们便一无所有。\n\n战场仲裁完毕，你有权保持沉默，但你造成的噪音已经够大了。
GFL2.Mokosh_Vanguard_Description=誓卫队中负责镇压暴乱、担任先锋的成员，大部分由本地居民武装而成，主要以数量来博取近身战取胜的机会。相比起人命，他们身上的装备更具价值。\n\n谁说炮灰不能有梦想？至少对他们来说，靠着军功往上爬并不是天方夜谭。
GFL2.Mokosh_Spec_Ops_Description=誓卫队中的精英成员，装备更精良，意志更坚定，内卷更严重。在誓卫队中负责火力压制，远距离作战能力优秀，作战风格残忍冷酷。可以说，他们正是代表了莫科什意识形态的狂热分子。\n\n不要质疑他们的忠诚，他们可不吝于让你见识一下忠诚的威力。
GFL2.Mokosh_Support_Description=誓卫队中担任后勤、医疗任务的成员。主要由老人和老兵组成，虽具备一定的自卫能力，但遇事也是最先逃离的一群人。\n\n平常能拉队友一把已经不错，关键时刻老油条脚底可抹了油。

# Niter
GFL2.Niter_PM=[少女前线 2] 妮特
GFL2.Niter_NPC_F=妮特（友方）
GFL2.Niter_NPC_E=妮特（敌对）

GFL2.Niter_Description=看起来是亲和力十足、总是微笑着的可爱少女。不管战场情况如何变化，她的慈爱与温柔都不会改变。\n\n声音足够温和，但不一定友善。

# Nyto
GFL2.Nyto_PM=[少女前线 2] 涅托
GFL2.Nyto_NPC_F=涅托（友方）
GFL2.Nyto_NPC_E=涅托（敌对）

GFL2.Nyto_Description=由人类改造而来的半机械实验体。永远平静冷淡，遵循各位大人们的指令行事，协助管理着帕拉蒂斯。\n\n平静的外表之下，流露出无声的威严。

# Sextans
GFL2.Paradeus_Sextans_PM=[少女前线 2] 六分仪
GFL2.Paradeus_Lose_Sextans_PM=[少女前线 2] 六分仪？

GFL2.Paradeus_Sextans_NPC_F=六分仪（友方）
GFL2.Paradeus_Sextans_NPC_E=六分仪（敌对）
GFL2.Paradeus_Lose_Sextans_NPC_F=六分仪？（友方）
GFL2.Paradeus_Lose_Sextans_NPC_E=六分仪？（敌对）

GFL2.Paradeus_Sextans_Description=优秀的棋手，懂得利用棋盘上的一切——包括敌人的棋子。\n\n您迟到了14分25秒31。
GFL2.Paradeus_Lose_Sextans_Description=遗忘了自己名姓的棋手，是否还能从容执子、窥探未来？\n\n告……诉……我……我……是……谁？

# Shellcracker
GFL2.Shellcracker_NPC_E=破壳者

GFL2.Shellcracker.Description=受坍塌辐射影响严重变异，植物特征与动物特征参半的怪物。破坏力与生命力极强，轻而易举就能撕碎装甲。\n\n这东西……需要晒太阳和浇水吗？
